// Bundles the agent runtimes (shared TS → single ESM files):
//   dist-agent/clearmind-mcp.mjs   local stdio MCP server
//   dist-agent/clearmind.mjs       CLI
//   api/mcp.js, api/v1.js          Vercel functions (hosted MCP + REST)
// firebase-admin and the MCP SDK stay external (installed from package.json).
import { build } from 'esbuild';

const common = { bundle: true, platform: 'node', format: 'esm', target: 'node20', external: ['firebase-admin', 'firebase-admin/*', '@modelcontextprotocol/sdk', '@modelcontextprotocol/sdk/*'], logLevel: 'warning', legalComments: 'none' };
const banner = { js: '// GENERATED by scripts/build-agent.mjs — do not edit. Source: server/, api-src/, cli/, shared/.\nimport { createRequire as __cr } from "module"; const require = __cr(import.meta.url);' };

await build({ ...common, entryPoints: ['server/stdio.ts'], outfile: 'dist-agent/clearmind-mcp.mjs', banner });
await build({ ...common, entryPoints: ['cli/clearmind.ts'], outfile: 'dist-agent/clearmind.mjs', banner });
await build({ ...common, entryPoints: { mcp: 'api-src/mcp.ts', v1: 'api-src/v1.ts' }, outdir: 'api', outExtension: { '.js': '.js' }, banner });
console.log('agent bundles built');
