// Adds `ndk { debugSymbolLevel 'FULL' }` to the release build type so the AAB carries
// native debug symbols (Play Console crash/ANR symbolication). android/ is generated by
// `expo prebuild` (gitignored), so this has to be a config plugin, not a manual edit.
const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = "debugSymbolLevel 'FULL'";

module.exports = function withReleaseDebugSymbols(config) {
  return withAppBuildGradle(config, (cfg) => {
    let src = cfg.modResults.contents;
    if (!src.includes(MARKER)) {
      const next = src.replace(/(buildTypes\s*\{[\s\S]*?release\s*\{)/, `$1\n            ndk { ${MARKER} }`);
      if (next === src) throw new Error('withReleaseDebugSymbols: release buildType not found in app/build.gradle');
      src = next;
    }
    cfg.modResults.contents = src;
    return cfg;
  });
};
