// GENERATED by scripts/build-agent.mjs — do not edit. Source: server/, api-src/, cli/, shared/.
import { createRequire as __cr } from "module"; const require = __cr(import.meta.url);

// api-src/oauth.ts
import { createHash, randomBytes } from "node:crypto";
import { getFirestore as getFirestore2 } from "firebase-admin/firestore";
import { getAuth } from "firebase-admin/auth";

// server/firestoreRepo.ts
import { getFirestore, FieldValue } from "firebase-admin/firestore";
import { initializeApp, cert, getApps, applicationDefault } from "firebase-admin/app";
import { readFileSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

// shared/data/collections.ts
var STORES = {
  PROJECTS: "projects",
  TASKS: "tasks",
  NOTES: "notes",
  HABITS: "habits",
  GOALS: "goals",
  MILESTONES: "milestones",
  LOGS: "logs",
  PROFILE: "profile",
  RANTS: "rants",
  MINDMAPS: "mindmaps",
  EVENTS: "events",
  DAILY_MAPPER: "dailymapper",
  DAILY_MAPPER_TEMPLATES: "dailymappertemplates",
  APPLICATIONS: "applications",
  IRIS_CONVERSATIONS: "iris_conversations",
  LEARNING_RESOURCES: "learningresources",
  LEARNING_FOLDERS: "learningfolders",
  LABELS: "labels",
  SECTIONS: "sections",
  COMMENTS: "comments",
  COMPLETIONS: "completions",
  ACTIVITY: "activity",
  PREFERENCES: "preferences",
  FILTERS: "filters"
};
var STORE_TO_FIRESTORE = {
  [STORES.TASKS]: "tasks",
  [STORES.PROJECTS]: "projects",
  [STORES.NOTES]: "notes",
  [STORES.HABITS]: "habits",
  [STORES.GOALS]: "goals",
  [STORES.MILESTONES]: "milestones",
  [STORES.LOGS]: "dailyLogs",
  [STORES.RANTS]: "rants",
  [STORES.EVENTS]: "events",
  [STORES.DAILY_MAPPER]: "timeblocks",
  [STORES.DAILY_MAPPER_TEMPLATES]: "timeblocktemplates",
  [STORES.MINDMAPS]: "mindmaps",
  [STORES.APPLICATIONS]: "applications",
  [STORES.IRIS_CONVERSATIONS]: "iris_conversations",
  [STORES.LEARNING_RESOURCES]: "learningResources",
  [STORES.LEARNING_FOLDERS]: "learningFolders",
  [STORES.LABELS]: "labels",
  [STORES.SECTIONS]: "sections",
  [STORES.COMMENTS]: "comments",
  [STORES.COMPLETIONS]: "completions",
  [STORES.ACTIVITY]: "activity",
  [STORES.PREFERENCES]: "preferences",
  [STORES.FILTERS]: "filters"
};
var FIRESTORE_TO_STORE = Object.entries(STORE_TO_FIRESTORE).reduce((acc, [local, firestore]) => {
  acc[firestore] = local;
  return acc;
}, {});

// server/firestoreRepo.ts
var DEFAULT_KEY_PATH = join(homedir(), ".config", "clearmind", "service-account.json");
function adminApp() {
  if (getApps().length) return getApps()[0];
  const raw = process.env.FIREBASE_SERVICE_ACCOUNT;
  if (raw) {
    const json = raw.trim().startsWith("{") ? raw : Buffer.from(raw, "base64").toString("utf8");
    return initializeApp({ credential: cert(JSON.parse(json)) });
  }
  const path = process.env.CLEARMIND_SERVICE_ACCOUNT || (existsSync(DEFAULT_KEY_PATH) ? DEFAULT_KEY_PATH : null);
  if (path) return initializeApp({ credential: cert(JSON.parse(readFileSync(path, "utf8"))) });
  return initializeApp({ credential: applicationDefault(), projectId: process.env.FIREBASE_PROJECT_ID });
}

// shared/agents/tokens.ts
var TOKEN_PREFIX = "cm_";
var B62 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
function secretFromBytes(bytes, len = 40) {
  let s = "";
  for (let i = 0; i < len; i++) s += B62[bytes[i % bytes.length] % 62];
  return s;
}
var makeToken = (uid, secret) => `${TOKEN_PREFIX}${uid}_${secret}`;
function parseToken(token) {
  if (typeof token !== "string" || !token.startsWith(TOKEN_PREFIX)) return null;
  const body = token.slice(TOKEN_PREFIX.length);
  const i = body.lastIndexOf("_");
  if (i <= 0) return null;
  const uid = body.slice(0, i);
  const secret = body.slice(i + 1);
  if (!/^[A-Za-z0-9]{20,128}$/.test(uid) || !/^[A-Za-z0-9]{32,}$/.test(secret)) return null;
  return { uid, secret };
}
var tokenPrefix = (token) => `${token.slice(0, 7)}\u2026${token.slice(-4)}`;
var SCOPES = [
  { scope: "tasks:read", label: "Read tasks", detail: "Inbox, Today, Upcoming, search, comments" },
  { scope: "tasks:write", label: "Create & edit tasks", detail: "Capture, update, complete, move, comment" },
  { scope: "tasks:delete", label: "Delete tasks", detail: "Single deletes (bulk needs \u201CBulk\u201D)", risky: true },
  { scope: "projects:read", label: "Read projects", detail: "Projects, sections, labels, progress" },
  { scope: "projects:write", label: "Manage projects", detail: "Create/rename/archive projects & sections" },
  { scope: "projects:delete", label: "Delete projects", detail: "Removes a project and its tasks", risky: true },
  { scope: "productivity:read", label: "Read productivity", detail: "Momentum, goals, streaks, history" },
  { scope: "notes:read", label: "Read notes", detail: "Notes vault: list, read, search, backlinks" },
  { scope: "notes:write", label: "Write notes", detail: "Create, edit, rename/move, import notes" },
  { scope: "notes:delete", label: "Delete notes", detail: "Remove notes (multiple needs confirmation)", risky: true },
  { scope: "bulk", label: "Bulk operations", detail: "Change or delete many items at once (with confirmation)", risky: true }
];
var SCOPE_PRESETS = [
  { id: "read", label: "Read only", scopes: ["tasks:read", "projects:read", "productivity:read", "notes:read"] },
  { id: "standard", label: "Standard (no deletes)", scopes: ["tasks:read", "tasks:write", "projects:read", "projects:write", "productivity:read", "notes:read", "notes:write"] },
  { id: "full", label: "Full access", scopes: ["tasks:read", "tasks:write", "tasks:delete", "projects:read", "projects:write", "projects:delete", "productivity:read", "notes:read", "notes:write", "notes:delete", "bulk"] }
];
var DEFAULT_RATE_LIMIT = 60;

// shared/agents/oauth.ts
var OAUTH_CODE_TTL_MS = 5 * 60 * 1e3;
var ALL_SCOPES = SCOPES.map((s) => s.scope);
var DEFAULT_CONNECTOR_SCOPES = SCOPE_PRESETS.find((p) => p.id === "standard").scopes;
function base64url(bytes) {
  let s = "";
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
async function verifyPkce(verifier, challenge, sha256Bytes) {
  if (!/^[A-Za-z0-9\-._~]{43,128}$/.test(verifier ?? "")) return false;
  return base64url(await sha256Bytes(verifier)) === challenge;
}
function isAllowedRedirect(uri) {
  let u;
  try {
    u = new URL(uri);
  } catch {
    return false;
  }
  if (u.hash) return false;
  if (u.protocol === "https:") return true;
  if (u.protocol === "http:" && (u.hostname === "localhost" || u.hostname === "127.0.0.1" || u.hostname === "[::1]")) return true;
  return /^[a-z][a-z0-9+.-]*:$/.test(u.protocol) && !["javascript:", "data:", "file:", "http:"].includes(u.protocol);
}
function redirectMatches(registered, uri) {
  if (registered.includes(uri)) return true;
  try {
    const u = new URL(uri);
    if (u.protocol !== "http:" || !["localhost", "127.0.0.1", "[::1]"].includes(u.hostname)) return false;
    return registered.some((r) => {
      try {
        const x = new URL(r);
        return x.protocol === u.protocol && x.hostname === u.hostname && x.pathname === u.pathname;
      } catch {
        return false;
      }
    });
  } catch {
    return false;
  }
}
function parseScopes(scope) {
  const want = String(scope ?? "").split(/[\s,]+/).filter(Boolean);
  const known = want.filter((s) => ALL_SCOPES.includes(s));
  return known.length ? [...new Set(known)] : DEFAULT_CONNECTOR_SCOPES;
}
function validateRegistration(body) {
  const uris = Array.isArray(body?.redirect_uris) ? body.redirect_uris.filter((x) => typeof x === "string") : [];
  if (!uris.length) return { ok: false, error: "invalid_redirect_uri", description: "redirect_uris is required" };
  const bad = uris.find((u) => !isAllowedRedirect(u));
  if (bad) return { ok: false, error: "invalid_redirect_uri", description: `Redirect URI not allowed: ${bad}` };
  if (uris.length > 10) return { ok: false, error: "invalid_client_metadata", description: "Too many redirect_uris" };
  const method = body.token_endpoint_auth_method ?? "none";
  if (method !== "none") return { ok: false, error: "invalid_client_metadata", description: 'Only public clients (token_endpoint_auth_method "none" with PKCE) are supported' };
  const name = String(body.client_name ?? "").trim().slice(0, 80) || hostLabel(uris[0]);
  return { ok: true, client: { client_name: name, redirect_uris: uris, ...typeof body.client_uri === "string" ? { client_uri: body.client_uri } : {} } };
}
function hostLabel(uri) {
  try {
    const h = new URL(uri).hostname.replace(/^www\./, "");
    if (h.endsWith("claude.ai") || h.endsWith("anthropic.com")) return "Claude";
    if (h.endsWith("chatgpt.com") || h.endsWith("openai.com")) return "ChatGPT";
    return h || "MCP client";
  } catch {
    return "MCP client";
  }
}
function protectedResourceMetadata(origin) {
  return {
    resource: `${origin}/api/mcp`,
    authorization_servers: [origin],
    scopes_supported: ALL_SCOPES,
    bearer_methods_supported: ["header"],
    resource_name: "ClearMind",
    resource_documentation: `${origin}/privacy.html`
  };
}
function authorizationServerMetadata(origin) {
  return {
    issuer: origin,
    authorization_endpoint: `${origin}/oauth/authorize`,
    token_endpoint: `${origin}/api/oauth/token`,
    registration_endpoint: `${origin}/api/oauth/register`,
    revocation_endpoint: `${origin}/api/oauth/revoke`,
    scopes_supported: ALL_SCOPES,
    response_types_supported: ["code"],
    response_modes_supported: ["query"],
    grant_types_supported: ["authorization_code", "refresh_token"],
    token_endpoint_auth_methods_supported: ["none"],
    revocation_endpoint_auth_methods_supported: ["none"],
    code_challenge_methods_supported: ["S256"],
    service_documentation: `${origin}/privacy.html`
  };
}
function redirectWith(uri, params) {
  const u = new URL(uri);
  for (const [k, v] of Object.entries(params)) if (v !== void 0 && v !== null && v !== "") u.searchParams.set(k, v);
  return u.toString();
}

// api-src/http.ts
async function readJson(req) {
  if (req.body !== void 0) return typeof req.body === "string" ? JSON.parse(req.body || "null") : req.body;
  const chunks = [];
  let size = 0;
  for await (const c of req) {
    size += c.length;
    if (size > 1e6) throw new Error("payload too large");
    chunks.push(c);
  }
  const raw = Buffer.concat(chunks).toString("utf8");
  return raw ? JSON.parse(raw) : null;
}
function sendJson(res, status, body) {
  res.statusCode = status;
  res.setHeader("Content-Type", "application/json");
  res.setHeader("Cache-Control", "no-store");
  res.end(JSON.stringify(body));
}

// api-src/oauth.ts
var db = null;
var fdb = () => db ??= getFirestore2(adminApp());
var sha = (s) => createHash("sha256").update(s).digest("hex");
var shaBytes = async (s) => new Uint8Array(createHash("sha256").update(s).digest());
var rand = (n) => secretFromBytes(randomBytes(n), n);
function originOf(req) {
  const host = req.headers["x-forwarded-host"] ?? req.headers.host ?? "clearmind.meertech.tech";
  const proto = req.headers["x-forwarded-proto"] ?? (host.startsWith("localhost") ? "http" : "https");
  return `${proto.split(",")[0]}://${host.split(",")[0]}`;
}
function cors(res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization, MCP-Protocol-Version");
}
var oauthError = (res, status, error, description) => sendJson(res, status, { error, error_description: description });
async function readForm(req) {
  if (req.body && typeof req.body === "object") return req.body;
  const raw = typeof req.body === "string" ? req.body : await new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (c) => chunks.push(c));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
  const type = String(req.headers["content-type"] ?? "");
  if (type.includes("application/json")) {
    try {
      return JSON.parse(raw || "{}");
    } catch {
      return {};
    }
  }
  return Object.fromEntries(new URLSearchParams(raw));
}
async function mintAccessToken(uid, scopes, clientId, clientName) {
  const token = makeToken(uid, rand(40));
  const hash = sha(token);
  await fdb().doc(`users/${uid}/agentTokens/${hash}`).set({
    id: hash,
    name: clientName,
    scopes,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    prefix: tokenPrefix(token),
    rateLimit: DEFAULT_RATE_LIMIT,
    revoked: false,
    via: "oauth",
    clientId
  });
  const refresh = `cmr_${rand(48)}`;
  await fdb().doc(`oauthRefresh/${sha(refresh)}`).set({ uid, clientId, clientName, scopes, accessHash: hash, createdAt: (/* @__PURE__ */ new Date()).toISOString() });
  return { access_token: token, token_type: "Bearer", refresh_token: refresh, scope: scopes.join(" ") };
}
async function handler(req, res) {
  cors(res);
  if (req.method === "OPTIONS") {
    res.statusCode = 204;
    return res.end();
  }
  const url = new URL(req.url ?? "/", "http://x");
  const route = url.searchParams.get("route") ?? url.pathname.replace(/^\/api\/oauth\/?/, "");
  const origin = originOf(req);
  try {
    if (route === "prm" && req.method === "GET") return sendJson(res, 200, protectedResourceMetadata(origin));
    if (route === "as" && req.method === "GET") return sendJson(res, 200, authorizationServerMetadata(origin));
    if (route === "register" && req.method === "POST") {
      const v = validateRegistration(await readJson(req));
      if ("error" in v) return oauthError(res, 400, v.error, v.description);
      const clientId = `cmc_${rand(24)}`;
      const now = Math.floor(Date.now() / 1e3);
      await fdb().doc(`oauthClients/${clientId}`).set({ ...v.client, createdAt: (/* @__PURE__ */ new Date()).toISOString() });
      return sendJson(res, 201, {
        client_id: clientId,
        client_id_issued_at: now,
        ...v.client,
        grant_types: ["authorization_code", "refresh_token"],
        response_types: ["code"],
        token_endpoint_auth_method: "none"
      });
    }
    if (route === "client" && req.method === "GET") {
      const clientId = url.searchParams.get("client_id") ?? "";
      const redirect = url.searchParams.get("redirect_uri") ?? "";
      const c = clientId ? await fdb().doc(`oauthClients/${clientId}`).get() : null;
      if (!c?.exists) return oauthError(res, 404, "invalid_client", "Unknown client");
      const data = c.data();
      if (!redirectMatches(data.redirect_uris ?? [], redirect)) return oauthError(res, 400, "invalid_request", "redirect_uri does not match the registered client");
      return sendJson(res, 200, { client_name: data.client_name, redirect_host: new URL(redirect).host });
    }
    if (route === "approve" && req.method === "POST") {
      const b = await readJson(req);
      const c = await fdb().doc(`oauthClients/${String(b?.client_id ?? "")}`).get();
      if (!c.exists) return oauthError(res, 400, "invalid_client", "Unknown client");
      const client = c.data();
      if (!redirectMatches(client.redirect_uris ?? [], String(b.redirect_uri ?? ""))) return oauthError(res, 400, "invalid_request", "redirect_uri mismatch");
      if (b.deny) return sendJson(res, 200, { redirect: redirectWith(b.redirect_uri, { error: "access_denied", state: b.state }) });
      if (b.code_challenge_method !== "S256" || !/^[A-Za-z0-9_-]{43}$/.test(String(b.code_challenge ?? ""))) return oauthError(res, 400, "invalid_request", "PKCE S256 code_challenge is required");
      let uid;
      try {
        uid = (await getAuth(adminApp()).verifyIdToken(String(b.id_token ?? ""))).uid;
      } catch {
        return oauthError(res, 401, "login_required", "Sign in to ClearMind again");
      }
      const scopes = parseScopes(Array.isArray(b.scopes) ? b.scopes.join(" ") : b.scope);
      const code = `cma_${rand(40)}`;
      await fdb().doc(`oauthCodes/${sha(code)}`).set({
        uid,
        clientId: b.client_id,
        clientName: client.client_name,
        redirectUri: b.redirect_uri,
        codeChallenge: b.code_challenge,
        scopes,
        resource: b.resource ?? null,
        expiresAt: Date.now() + OAUTH_CODE_TTL_MS,
        used: false
      });
      return sendJson(res, 200, { redirect: redirectWith(b.redirect_uri, { code, state: b.state, iss: origin }) });
    }
    if (route === "token" && req.method === "POST") {
      const f = await readForm(req);
      if (f.grant_type === "authorization_code") {
        const ref = fdb().doc(`oauthCodes/${sha(String(f.code ?? ""))}`);
        const claim = await fdb().runTransaction(async (tx) => {
          const s = await tx.get(ref);
          if (!s.exists) return null;
          const d = s.data();
          tx.update(ref, { used: true });
          return d;
        });
        if (!claim || claim.used || claim.expiresAt < Date.now()) return oauthError(res, 400, "invalid_grant", "Authorization code is invalid or expired");
        if (f.client_id && f.client_id !== claim.clientId) return oauthError(res, 400, "invalid_grant", "client_id mismatch");
        if (f.redirect_uri && f.redirect_uri !== claim.redirectUri) return oauthError(res, 400, "invalid_grant", "redirect_uri mismatch");
        if (!await verifyPkce(String(f.code_verifier ?? ""), claim.codeChallenge, shaBytes)) return oauthError(res, 400, "invalid_grant", "PKCE verification failed");
        await ref.delete().catch(() => void 0);
        return sendJson(res, 200, await mintAccessToken(claim.uid, claim.scopes, claim.clientId, claim.clientName));
      }
      if (f.grant_type === "refresh_token") {
        const ref = fdb().doc(`oauthRefresh/${sha(String(f.refresh_token ?? ""))}`);
        const s = await ref.get();
        if (!s.exists) return oauthError(res, 400, "invalid_grant", "Refresh token is invalid");
        const d = s.data();
        if (f.client_id && f.client_id !== d.clientId) return oauthError(res, 400, "invalid_grant", "client_id mismatch");
        const old = fdb().doc(`users/${d.uid}/agentTokens/${d.accessHash}`);
        const oldSnap = await old.get();
        if (!oldSnap.exists || oldSnap.data()?.revoked) {
          await ref.delete();
          return oauthError(res, 400, "invalid_grant", "Access was revoked");
        }
        await old.set({ revoked: true, revokedAt: (/* @__PURE__ */ new Date()).toISOString() }, { merge: true });
        await ref.delete();
        return sendJson(res, 200, await mintAccessToken(d.uid, d.scopes, d.clientId, d.clientName));
      }
      return oauthError(res, 400, "unsupported_grant_type", "Use authorization_code or refresh_token");
    }
    if (route === "revoke" && req.method === "POST") {
      const f = await readForm(req);
      const t = String(f.token ?? "");
      const parsed = parseToken(t);
      if (parsed) await fdb().doc(`users/${parsed.uid}/agentTokens/${sha(t)}`).set({ revoked: true, revokedAt: (/* @__PURE__ */ new Date()).toISOString() }, { merge: true }).catch(() => void 0);
      else if (t.startsWith("cmr_")) {
        const ref = fdb().doc(`oauthRefresh/${sha(t)}`);
        const s = await ref.get();
        if (s.exists) {
          const d = s.data();
          await fdb().doc(`users/${d.uid}/agentTokens/${d.accessHash}`).set({ revoked: true, revokedAt: (/* @__PURE__ */ new Date()).toISOString() }, { merge: true });
          await ref.delete();
        }
      }
      res.statusCode = 200;
      return res.end();
    }
    return oauthError(res, 404, "not_found", `Unknown OAuth route "${route}"`);
  } catch (e) {
    console.error("oauth error", route, e?.message);
    return oauthError(res, 500, "server_error", "Internal error");
  }
}
export {
  handler as default,
  originOf
};
